version: '4.17'
name: "Expennies"

services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
      args:
        USER_ID: '${WWWUSER:-1000}'
        GROUP_ID: '${WWWGROUP:-1000}'
        USER: '${USER:-whoami}'
    container_name: expennies-app
    restart: always
    working_dir: /var/www/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../:/var/www
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9003:9003"
    
  nginx:
    image: nginx:1.23.4-alpine
    container_name: expennies-nginx
    restart: always
    ports:
      - "8003:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: expennies-db
    image: mysql:8.0.32
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"